on:
  push:
    tags:
      - "v*"

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.os }}-${{ hashFiles('build.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ matrix.os }}-

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: build apk
        run: ./gradlew :android:build -PbarsUrl=https://kotlinbars.jamesward.dev/api/bars

      - name: upload apk
        uses: actions/upload-artifact@v2
        with:
          name: kotlin-bars.apk
          path: android/build/outputs/apk/release/android-release-unsigned.apk

      - name: release apk
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: kotlin-bars.apk
          file: android/build/outputs/apk/release/android-release-unsigned.apk
          tag: ${{ github.ref }}
